# Generated by Django 5.2.15 on 2026-06-10 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='검색 주제')),
                ('final_summary', models.TextField(verbose_name='최종 요약')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='신뢰도')),
                ('fact_checked', models.BooleanField(default=False, verbose_name='팩트체크 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
            ],
            options={
                'verbose_name': '요약 보고서',
                'verbose_name_plural': '요약 보고서 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConflictRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='충돌 주제')),
                ('claim_a', models.TextField(verbose_name='주장 A')),
                ('claim_b', models.TextField(verbose_name='주장 B')),
                ('source_a', models.CharField(max_length=255, verbose_name='출처 A')),
                ('source_b', models.CharField(max_length=255, verbose_name='출처 B')),
                ('verdict', models.TextField(blank=True, verbose_name='검증 결과')),
                ('resolved', models.BooleanField(default=False, verbose_name='해결됨')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='news.summaryreport', verbose_name='보고서')),
            ],
            options={
                'verbose_name': '충돌 기록',
                'verbose_name_plural': '충돌 기록 목록',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='제목')),
                ('content', models.TextField(verbose_name='본문')),
                ('source', models.CharField(choices=[('rss', 'RSS'), ('pdf', 'PDF'), ('url', 'URL')], max_length=10, verbose_name='소스 타입')),
                ('source_name', models.CharField(max_length=255, verbose_name='출처명')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('published', models.CharField(blank=True, max_length=100, null=True, verbose_name='발행일')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.summaryreport', verbose_name='보고서')),
            ],
            options={
                'verbose_name': '기사',
                'verbose_name_plural': '기사 목록',
            },
        ),
    ]
