# Generated by Django 5.2.15 on 2026-06-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryreport',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='오류 메시지'),
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('running', '실행 중'), ('done', '완료'), ('error', '오류')], default='pending', max_length=10, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='summaryreport',
            name='final_summary',
            field=models.TextField(blank=True, verbose_name='최종 요약'),
        ),
    ]
